import React, { memo } from 'react';
import { useTheme } from 'styled-components/native';
import { IconName, IconProps, IconTypeOptions } from './types';
import * as Icons from './exports';
import theme from '../../global/styles/theme';

const getIcon = (avatarType: IconName) => {
  const icons: IconTypeOptions = {
    wallet: Icons.Wallet,
    notes: Icons.Notes,
    building_store: Icons.BuildingStore,
    shopping_cart_discount: Icons.ShoppingCartDiscount,
    copy: Icons.Copy,
    brand_instagram: Icons.BrandInstagram,
    brand_facebook: Icons.BrandFacebook,
    brand_whatsapp: Icons.BrandWhatsapp,
    cash: Icons.Cash,
    directions: Icons.Directions,
    file_description: Icons.FileDescription,
    user: Icons.User,
    filter: Icons.Filter,
    photo_x: Icons.PhotoX,
    calendar_due: Icons.CalendarDue,
    trash: Icons.Trash,
    divide: Icons.Divide,
    credit_card: Icons.CreditCard,
    eye: Icons.Eye,
    eye_closed: Icons.EyeClosed,
    lock: Icons.Lock,
    address_book: Icons.AddressBook,
    bell: Icons.Bell,
    calendar_event: Icons.CalendarEvent,
    chart_pie: Icons.ChartPie,
    device_desktop: Icons.DeviceDesktop,
    exchange: Icons.Exchange,
    help_circle: Icons.HelpCircle,
    layout_dashboard: Icons.LayoutDashboard,
    logout: Icons.Logout,
    moon: Icons.Moon,
    package: Icons.Package,
    receipt2: Icons.Receipt2,
    report: Icons.Report,
    rotate2: Icons.Rotate2,
    shopping_cart: Icons.ShoppingCart,
    sun: Icons.Sun,
    user_circle: Icons.UserCircle,
    users: Icons.Users,
    percentage: Icons.Percentage,
    arrow_left: Icons.ArrowLeft,
    arrow_right: Icons.ArrowRight,
    phone: Icons.Phone,
    mail: Icons.Mail,
    map_pin_filled: Icons.MapPinFilled,
    one_two_three: Icons.OneTwoThree,
    home: Icons.Home,
    building_community: Icons.BuildingCommunity,
    location: Icons.Location,
    mail_pin: Icons.MailPin,
    map: Icons.Map,
    tag: Icons.Tag,
    device_mobile: Icons.DeviceMobile,
    user_plus: Icons.UserPlus,
    pencil: Icons.Pencil,
    clock: Icons.Clock,
    id_badge_2: Icons.IdBadge2,
    asset: Icons.Asset,
    mood_search: Icons.MoodSearch,
    gift: Icons.Gift,
    users_group: Icons.UsersGroup,
    message: Icons.Message,
    calendar_check: Icons.CalendarCheck,
    heart: Icons.Heart,
    user_check: Icons.UserCheck,
    arrow_down_left: Icons.ArrowDownLeft,
    circle: Icons.Circle,
    circle_check: Icons.CircleCheck,
    phone_outgoing: Icons.PhoneOutgoing,
    droplet: Icons.Droplet,
    wind: Icons.Wind,
    link: Icons.Link,
    archive: Icons.Archive,
    arrow_up_left: Icons.ArrowDownLeft,
    x_icon: Icons.XIcon,
    chevron_left: Icons.ChevronLeft,
    plus: Icons.Plus,
    send: Icons.Send,
    edit: Icons.Edit,
    chevron_down: Icons.ChevronDown,
    menu_2: Icons.Menu2,
    exclamation_circle: Icons.ExclamationCircle,
    circle_plus: Icons.CirclePlus,
    circle_arrow_down: Icons.CircleArrowDown,
    circle_arrow_up: Icons.CircleArrowUp,
    info_circle: Icons.InfoCircle,
    file: Icons.File,
    layers_linked: Icons.LayersLinked,
    search: Icons.Search,
    ticket: Icons.Ticket,
    chevron_right: Icons.ChevronRight,
    trending_up: Icons.TrendingUp,
    rotate_clockwise: Icons.RotateClockWise,
    share_2: Icons.Share2,
    minus: Icons.Minus,
    category: Icons.Category,
    brand_mastercard: Icons.BrandMastercard,
    chart_infographic: Icons.ChartInfoGraphic,
    ladder: Icons.Ladder,
    mood_x: Icons.MoodX,
    shopping_cart_x: Icons.ShoppingCartX,
    timeline_event: Icons.TimelineEvent,
    calendar_dollar: Icons.CalendarDollar,
    discount: Icons.Discount,
    mood_dollar: Icons.MoodDollar,
    shopping_cart_plus: Icons.ShoppingCartPlus,
    list_check: Icons.ListCheck,
    quote: Icons.Quote,
    cake: Icons.Cake,
    star: Icons.Star,
    shopping_bag: Icons.ShoppingBag,
    adjustments_horizontal: Icons.AdjustmentsHorizontal,
    checklist: Icons.Checklist,
    settings: Icons.Settings,
    external_link: Icons.ExternalLink,
    discount2: Icons.Discount2,
    discount_check: Icons.DiscountCheck,
    packages: Icons.Packages,
    chevron_up: Icons.ChevronUp,
    circle_minus: Icons.CircleMinus,
    message_circle_2: Icons.MessageCircle2,
    sunglasses: Icons.Sunglasses,
    palette: Icons.Palette,
    device_mobile_message: Icons.DeviceMobileMessage,
    trophy: Icons.Trophy,
    rotate_clockwise_2: Icons.RotateClockWise2,
    alert_circle: Icons.AlertCircle,
    eye_off: Icons.EyeOff,
    file_barcode: Icons.FileBarcode,
    user_x: Icons.UserX,
    download: Icons.Download,
    receipt: Icons.Receipt,
    printer: Icons.Printer,
    user_search: Icons.UserSearch,
    user_off: Icons.UserOff,
    circle_check_filled: Icons.CircleCheckFilled,
    clock_hour_3: Icons.ClockHour3,
    dots_vertical: Icons.DotsVertical,
    zoom_in_area: Icons.ZoomInArea,
    edit_circle: Icons.EditCircle,
    package_export: Icons.PackageExport,
    package_import: Icons.PackageImport,
    plus_minus: Icons.PlusMinus,
    refresh: Icons.Refresh,
    mood_check: Icons.MoodCheck,
    package_off: Icons.PackageOff,
    layout_grid: Icons.LayoutGrid,
    layout_list: Icons.LayoutList,
    database_search: Icons.DatabaseSearch,
    eraser: Icons.Eraser,
    shopping_cart_off: Icons.ShoppingCartOff,
    cash_off: Icons.CashOff,
    tags: Icons.Tags,
    wallet_off: Icons.WalletOff,
    coins: Icons.Coins,
    coin_off: Icons.CoinOff,
    pig_money: Icons.PigMoney,
    moneybag: Icons.Moneybag,
    map2: Icons.Map2,
    mood_heart: Icons.MoodHeart,
    heart_plus: Icons.HeartPlus,
    history: Icons.History,
    calendar_heart: Icons.CalendarHeart,
    scan_eye: Icons.ScanEye,
    circle_x: Icons.CircleX,
    user_heart: Icons.UserHeart,
    calendar_plus: Icons.CalendarPlus,
    user_star: Icons.UserStar,
    calendar: Icons.Calendar,
    messages: Icons.Messages,
    message_plus: Icons.MessagePlus,
    message_off: Icons.MessageOff,
    speakerphone: Icons.Speakerphone,
    address_book_off: Icons.AddressBookOff,
    database_minus: Icons.DatabaseMinus,
    chart_pie_off: Icons.ChartPieOff,
    check: Icons.Check,
    hourglass: Icons.Hourglass,
    device_mobile_up: Icons.DeviceMobileUp,
    coin: Icons.Coin,
    car: Icons.Car,
    qrcode: Icons.Qrcode,
    history_off: Icons.HistoryOff,
    barcode: Icons.Barcode,
    dialpad: Icons.Dialpad,
    camera: Icons.Camera,
    search_off: Icons.SearchOff,
    photo: Icons.Photo,
    wifi: Icons.Wifi,
    sun_off: Icons.SunOff,
    device_mobile_off: Icons.DeviceMobibleOff,
    bolt: Icons.Bolt,
    mood_smile: Icons.MoodSmile,
    mood_empty: Icons.MoodEmpty,
    mood_sad: Icons.MoodSad,
    traffic_cone_off: Icons.TrafficConeOff,
    car_crash: Icons.CarCrash,
    id_off: Icons.IdOff,
    tool: Icons.Tool,
    mood_sad_dizzy: Icons.MoodSadDizzy,
    arrow_back_up: Icons.ArrowBackUp,
    notes_off: Icons.NotesOff,
    paperclip: Icons.PaperClip,
    brand_speedtest: Icons.BrandSpeedTest,
    wheel: Icons.Wheel,
    steering_wheel: Icons.SteeringWheel,
  };

  if (icons[avatarType]) {
    return icons[avatarType];
  }

  return null;
};

export const Icon = memo(({ name, color, size }: IconProps) => {

  if (!name) {
    return <></>;
  }

  const TrComponent = getIcon(name);

  if (!TrComponent) {
    return;
  }

  return (
    <TrComponent
      color={color || theme.colors.white}
      width={size }
      height={size}
    />
  );
});
